// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc5176.Billobot.subsystems;
import org.usfirst.frc5176.Billobot.RobotMap;
import org.usfirst.frc5176.Billobot.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;
/**
 *
 */
public class DriveTrain extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController rightMotor = RobotMap.driveTrainRightMotor;
    SpeedController leftMotor = RobotMap.driveTrainLeftMotor;
    RobotDrive robotDrive21 = RobotMap.driveTrainRobotDrive21;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    
    /*
     *	Last edited Jan 28
     *	Function finds average coordinates of joysticks
     *	then sets motors to appropriate speeds 
     *	
     *	Does ANYONE know what the max x and y coordinates are for the joysticks?
     *	I am assuming it is [-1,1] on both axes but if I am wrong the robot might
     *	move really slowly.
     *
     *	Original function:
     *	
     *	public void tankDrive(Joystick stick1, Joystick stick2) {
     *		robotDrive21.tankDrive(stick1, stick2);
     *	}
     *
     *	Written by Ben James
     */
    public void tankDrive(Joystick stick1, Joystick stick2) {
        double x = (stick0.getX(null) + stick1.getX(null)) / 2.;
	double y = (stick0.getY(null) + stick1.getY(null)) / 2.;
	leftMotor.set((y + x) / 2.);
	rightMotor.set((y - x) / 2.);
    }
    
    public void driveStraight(double speed) {
        robotDrive21.tankDrive(speed, speed);
    }
}
